@ECHO OFF

ECHO START P1 FROM C++BUILDER IDE
PAUSE

ECHO START NEXT 5 PROCESSES
PAUSE

START P2\XME.INJ_Ring.exe
START P3\XME.INJ_Ring.exe
START P4\XME.INJ_Ring.exe
START P5\XME.INJ_Ring.exe
START P6\XME.INJ_Ring.exe
