@ECHO OFF

ECHO START P6 FROM C++BUILDER IDE
PAUSE

ECHO START NEXT 5 PROCESSES
PAUSE

START P1\XME.GD_Ring.exe
START P2\XME.GD_Ring.exe
START P3\XME.GD_Ring.exe
START P4\XME.GD_Ring.exe
START P5\XME.GD_Ring.exe
